# -*- coding: utf-8 -*-
"""Generate the A29 solution file from the R3 time parent (frozen card
workbench/continuous_attention/anchor29-a1/{mechanism.md,config.json}).

Derivation:
  1. verify the parent SHA-256 == A5C679D7... (config.json frozen parent);
  2. rename the R3/A2 calibration entry to _r3_a2_calibration_attention
     (its body is kept bitwise; all validated old training is preserved);
  3. append the A29 block (closed-form driver + dual gates + new entry).
The generated file must expose the same six public APIs; S=0 / failure
paths never touch the returned state (bitwise R3 restore).
"""

import hashlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
PARENT = ROOT / "solutions/v162_attention_r3-rotation-center_allgates/solution.py"
BLOCK = ROOT / "workbench/continuous_attention/anchor29-a1/a29_block.py"
OUT_DIR = ROOT / "solutions/v163_attention_a29-final-residual-s"
OUT = OUT_DIR / "solution.py"
PARENT_SHA = "A5C679D7A2B349A879B2019B4A613244F5FEA7050E407B6475B9E29BD1C146DC"

RENAME_ANCHOR = (
    'def hif4_calibration_attention(\n'
    '    calib_qkv_list: list,\n'
    '    q_num_heads: int,\n'
    '    kv_num_heads: int,\n'
    '    head_dim: int,\n'
    ') -> dict[str, Any]:\n'
    '    """v189 stack calibration + gated learned rotation (A2 frozen config)."""\n'
)
RENAME_REPLACEMENT = (
    'def _r3_a2_calibration_attention(\n'
    '    calib_qkv_list: list,\n'
    '    q_num_heads: int,\n'
    '    kv_num_heads: int,\n'
    '    head_dim: int,\n'
    ') -> dict[str, Any]:\n'
    '    """v189 stack calibration + gated learned rotation (A2 frozen config).\n'
    '\n'
    '    A29 derivation: original R3 entry, renamed verbatim (bitwise body).\n'
    '    """\n'
)

HEADER = (
    '# v163_attention_a29-final-residual-s: R3 parent (SHA A5C679D7) + A29\n'
    '# final-output-residual QK inverse-pair compensation (anchor29-a1).\n'
    '# Generated by workbench/continuous_attention/anchor29-a1/gen_solution.py.\n'
    '# All validated R3 old training is preserved; A29 only overwrites\n'
    '# learned_rotation/learned_center when both hard-output gates pass.\n'
    '\n'
)


def main() -> int:
    parent_bytes = PARENT.read_bytes()
    sha = hashlib.sha256(parent_bytes).hexdigest().upper()
    if sha != PARENT_SHA:
        print(f"[gen_solution] FATAL: parent SHA mismatch: {sha}")
        return 1
    parent_src = parent_bytes.decode("utf-8")  # CRLF preserved verbatim
    crlf_anchor = RENAME_ANCHOR.replace("\n", "\r\n")
    crlf_replacement = RENAME_REPLACEMENT.replace("\n", "\r\n")
    count = parent_src.count(crlf_anchor)
    if count != 1:
        print(f"[gen_solution] FATAL: rename anchor found {count} times (expected 1)")
        return 1
    block_src = BLOCK.read_text(encoding="utf-8").rstrip("\n")
    generated = parent_src.replace(crlf_anchor, crlf_replacement, 1)
    generated = generated.rstrip("\r\n") + "\r\n\r\n\r\n" + block_src.replace("\n", "\r\n") + "\r\n"
    generated = HEADER.replace("\n", "\r\n") + generated
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT.write_bytes(generated.encode("utf-8"))

    out_sha = hashlib.sha256(OUT.read_text(encoding="utf-8").encode("utf-8")).hexdigest().upper()
    print(f"[gen_solution] parent OK ({sha[:12]})")
    print(f"[gen_solution] wrote {OUT} ({OUT.stat().st_size} bytes)")
    print(f"[gen_solution] output SHA-256: {out_sha}")

    # static sanity: six public APIs + renamed base present exactly once each
    import re
    for api in [
        "hif4_calibration_and_quantize_weight",
        "hif4_dynamic_quantize_activation",
        "hif4_calibration_attention",
        "hif4_dynamic_quantize_q",
        "hif4_dynamic_quantize_k",
        "hif4_dynamic_quantize_v",
    ]:
        n = len(re.findall(rf"^def {api}\(", generated, flags=re.M))
        print(f"[gen_solution] def {api}: {n} definition(s)")
    n_base = len(re.findall(r"^def _r3_a2_calibration_attention\(", generated, flags=re.M))
    print(f"[gen_solution] def _r3_a2_calibration_attention: {n_base}")
    if n_base != 1:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
