"""Build the standard-Linear Attention probe solutions from archived sources.

The active plan deliberately reuses each archived Attention implementation and
only replaces the two Linear APIs with the already verified v162 standard
codec.  The replacement is appended as the final module definition block so
the generated file remains a self-contained, single-file solution.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
STANDARD_LINEAR_SOURCE = (
    ROOT
    / "solutions"
    / "v162_attention_r1-v189-attnstack-recovery_officialNA_timeNA"
    / "solution.py"
)
STANDARD_LINEAR_MARKER = (
    "# v162-independent Attention branch override "
    "(A agent, RECOVERY step R1):"
)


# Keep this table as the single source of truth for both build.py and
# verify.py.  v194 was generated before the plan was updated with its official
# result; its retained output is intentionally outside this active table.
CANDIDATES = (
    {
        "name": "standard-linear_v190-attn",
        "attention_source": (
            ROOT
            / "solutions"
            / "20260908_v190_attn-diag-reciprocal-balance_scoreNA_timeNA"
            / "solution.py"
        ),
        "output_dir": ROOT
        / "solutions"
        / "20260908_standard-linear_v190-attn_scoreNA_timeNA",
    },
    {
        "name": "standard-linear_v191-attn",
        "attention_source": (
            ROOT
            / "solutions"
            / "20260908_v191_attn-block-triangular-transport_scoreNA_timeNA"
            / "solution.py"
        ),
        "output_dir": ROOT
        / "solutions"
        / "20260908_standard-linear_v191-attn_scoreNA_timeNA",
    },
    {
        "name": "standard-linear_v192-attn",
        "attention_source": (
            ROOT
            / "solutions"
            / "20260908_v192_attn-full-reciprocal-residual_scoreNA_timeNA"
            / "solution.py"
        ),
        "output_dir": ROOT
        / "solutions"
        / "20260908_standard-linear_v192-attn_scoreNA_timeNA",
    },
    {
        "name": "standard-linear_v195-attn",
        "attention_source": (
            ROOT
            / "solutions"
            / "20260908_v195_attn-a2-center-gradient-aggregate_scoreNA_timeNA"
            / "solution.py"
        ),
        "output_dir": ROOT
        / "solutions"
        / "20260908_standard-linear_v195-attn_scoreNA_timeNA",
    },
    {
        "name": "standard-linear_v229-attn",
        "attention_source": (
            ROOT
            / "solutions"
            / "20260910_v229_attention-amc1-k-mean-recenter_rejected_scoreNA_timeNA"
            / "solution.py"
        ),
        "output_dir": ROOT
        / "solutions"
        / "20260910_standard-linear_v229-attn_scoreNA_timeNA",
    },
    {
        "name": "standard-linear_v234-attn",
        "attention_source": (
            ROOT
            / "solutions"
            / "20260910_v234_attention-agr1-general-reciprocal_scoreNA_timeNA"
            / "solution.py"
        ),
        "output_dir": ROOT
        / "solutions"
        / "20260910_standard-linear_v234-attn_scoreNA_timeNA",
    },
)


def _sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _read_utf8(path: Path) -> str:
    if not path.is_file():
        raise FileNotFoundError(path)
    return path.read_text(encoding="utf-8")


def _extract_standard_linear_tail(source: str) -> str:
    marker_count = source.count(STANDARD_LINEAR_MARKER)
    if marker_count != 1:
        raise ValueError(
            "standard Linear source must contain exactly one R1 override marker; "
            f"found {marker_count}"
        )
    tail = source[source.index(STANDARD_LINEAR_MARKER) :].lstrip()
    required = (
        "def hif4_calibration_and_quantize_weight(",
        "def hif4_dynamic_quantize_activation(",
        "def _branch_standard_params(",
        "def _branch_encode_standard_hif4(",
    )
    missing = [token for token in required if token not in tail]
    if missing:
        raise ValueError(f"standard Linear tail is incomplete: {missing}")
    return tail


def _build_candidate(
    *,
    attention_source: Path,
    output_dir: Path,
    standard_tail: str,
    standard_source_sha256: str,
) -> dict[str, str]:
    attention_bytes = attention_source.read_bytes()
    attention_text = attention_bytes.decode("utf-8")
    generated = (
        attention_text.rstrip()
        + "\n\n"
        + "# ---------------------------------------------------------------------------\n"
        + "# GENERATED BY workbench/standard_linear_attention_probes/build.py\n"
        + f"# standard Linear source SHA256: {standard_source_sha256}\n"
        + "# The appended R1 block shadows only the two Linear APIs.\n"
        + "# ---------------------------------------------------------------------------\n"
        + standard_tail.rstrip()
        + "\n"
    )

    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / "solution.py"
    output_path.write_text(generated, encoding="utf-8", newline="\n")
    return {
        "output": output_path.relative_to(ROOT).as_posix(),
        "attention_source": attention_source.relative_to(ROOT).as_posix(),
        "attention_source_sha256": _sha256_bytes(attention_bytes),
        "output_sha256": _sha256_bytes(generated.encode("utf-8")),
    }


def main() -> int:
    standard_source_bytes = STANDARD_LINEAR_SOURCE.read_bytes()
    standard_source_text = standard_source_bytes.decode("utf-8")
    standard_tail = _extract_standard_linear_tail(standard_source_text)
    standard_source_sha256 = _sha256_bytes(standard_source_bytes)
    standard_tail_sha256 = _sha256_bytes(standard_tail.encode("utf-8"))

    manifest: dict[str, object] = {
        "standard_linear_source": STANDARD_LINEAR_SOURCE.relative_to(ROOT).as_posix(),
        "standard_linear_source_sha256": standard_source_sha256,
        "standard_linear_tail_sha256": standard_tail_sha256,
        "candidates": [],
    }

    for spec in CANDIDATES:
        if not isinstance(spec["attention_source"], Path):
            raise TypeError("candidate attention_source must be a Path")
        record = {
            "name": spec["name"],
            **_build_candidate(
                attention_source=spec["attention_source"],
                output_dir=spec["output_dir"],
                standard_tail=standard_tail,
                standard_source_sha256=standard_source_sha256,
            ),
        }
        manifest["candidates"].append(record)  # type: ignore[union-attr]
        print(f"{record['name']}: {record['output']} ({record['output_sha256']})")

    manifest_path = Path(__file__).resolve().with_name("build-manifest.json")
    manifest_path.write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    print(f"manifest: {manifest_path.relative_to(ROOT).as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
