"""Statically verify the generated standard-Linear Attention solutions.

This check intentionally does not load the 4B cache or execute calibration.
The active plan's construction step only needs to prove that each generated
single-file solution is the archived Attention source plus the verified v162
standard Linear tail, with all six public APIs still present.
"""

from __future__ import annotations

import ast
import hashlib
import json
from pathlib import Path
from typing import Any

from build import (  # noqa: E402
    CANDIDATES,
    ROOT,
    STANDARD_LINEAR_MARKER,
    STANDARD_LINEAR_SOURCE,
    _extract_standard_linear_tail,
)


PUBLIC_APIS = {
    "hif4_calibration_and_quantize_weight": 3,
    "hif4_dynamic_quantize_activation": 3,
    "hif4_calibration_attention": 4,
    "hif4_dynamic_quantize_q": 5,
    "hif4_dynamic_quantize_k": 5,
    "hif4_dynamic_quantize_v": 5,
}
LINEAR_APIS = {
    "hif4_calibration_and_quantize_weight",
    "hif4_dynamic_quantize_activation",
}
ATTENTION_APIS = set(PUBLIC_APIS) - LINEAR_APIS
GENERATED_MARKER = "# GENERATED BY workbench/standard_linear_attention_probes/build.py"


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _relative(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def _function_defs(tree: ast.Module) -> dict[str, list[ast.FunctionDef | ast.AsyncFunctionDef]]:
    result: dict[str, list[ast.FunctionDef | ast.AsyncFunctionDef]] = {}
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            result.setdefault(node.name, []).append(node)
    return result


def _positional_arity(node: ast.FunctionDef | ast.AsyncFunctionDef) -> int:
    return len(node.args.posonlyargs) + len(node.args.args)


def _check_imports(tree: ast.Module) -> None:
    forbidden = {"importlib", "solutions", "workbench", "evaluator"}
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                root = alias.name.split(".", 1)[0]
                if root in forbidden:
                    raise AssertionError(f"repository-dependent import: {alias.name}")
        elif isinstance(node, ast.ImportFrom):
            if node.level:
                raise AssertionError("relative imports are not allowed")
            root = (node.module or "").split(".", 1)[0]
            if root in forbidden:
                raise AssertionError(f"repository-dependent import: {node.module}")


def _expected_generated_text(attention_source: Path, standard_tail: str, standard_sha: str) -> str:
    source = attention_source.read_text(encoding="utf-8")
    return (
        source.rstrip()
        + "\n\n"
        + "# ---------------------------------------------------------------------------\n"
        + GENERATED_MARKER
        + "\n"
        + f"# standard Linear source SHA256: {standard_sha}\n"
        + "# The appended R1 block shadows only the two Linear APIs.\n"
        + "# ---------------------------------------------------------------------------\n"
        + standard_tail.rstrip()
        + "\n"
    )


def _check_one(spec: dict[str, Any], standard_tail: str, standard_sha: str, manifest: dict[str, Any]) -> None:
    name = str(spec["name"])
    attention_source = Path(spec["attention_source"])
    output_path = Path(spec["output_dir"]) / "solution.py"
    if not attention_source.is_file():
        raise FileNotFoundError(attention_source)
    if not output_path.is_file():
        raise FileNotFoundError(output_path)

    output_bytes = output_path.read_bytes()
    output_text = output_path.read_text(encoding="utf-8")
    expected_text = _expected_generated_text(attention_source, standard_tail, standard_sha)
    if output_text != expected_text:
        raise AssertionError("generated file is not an exact source-plus-tail composition")

    tree = ast.parse(output_text, filename=str(output_path))
    _check_imports(tree)
    definitions = _function_defs(tree)
    marker_line = output_text[: output_text.index(GENERATED_MARKER)].count("\n") + 1
    for api, arity in PUBLIC_APIS.items():
        nodes = definitions.get(api, [])
        if not nodes:
            raise AssertionError(f"missing public API: {api}")
        last = nodes[-1]
        if _positional_arity(last) != arity:
            raise AssertionError(
                f"{api} has {_positional_arity(last)} positional arguments, expected {arity}"
            )
        if api in LINEAR_APIS and last.lineno <= marker_line:
            raise AssertionError(f"{api} is not supplied by the appended Linear tail")
        if api in ATTENTION_APIS and last.lineno > marker_line:
            raise AssertionError(f"Attention API {api} was redefined by the Linear tail")

    if output_text.count(STANDARD_LINEAR_MARKER) < 2:
        raise AssertionError("generated file does not contain both source and appended R1 markers")
    if GENERATED_MARKER not in output_text:
        raise AssertionError("missing generated provenance marker")

    manifest_records = {
        str(item["name"]): item for item in manifest.get("candidates", [])
    }
    record = manifest_records.get(name)
    if record is None:
        raise AssertionError("candidate missing from build manifest")
    if record.get("output") != _relative(output_path):
        raise AssertionError("manifest output path mismatch")
    if record.get("output_sha256") != _sha256(output_bytes):
        raise AssertionError("manifest output SHA256 mismatch")


def main() -> int:
    standard_bytes = STANDARD_LINEAR_SOURCE.read_bytes()
    # read_text uses universal-newline normalization, matching build.py's
    # source read.  The bytes are still used for the provenance SHA below.
    standard_text = STANDARD_LINEAR_SOURCE.read_text(encoding="utf-8")
    standard_tail = _extract_standard_linear_tail(standard_text)
    standard_sha = _sha256(standard_bytes)
    manifest_path = Path(__file__).with_name("build-manifest.json")
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))

    failures = 0
    for raw_spec in CANDIDATES:
        spec = dict(raw_spec)
        name = str(spec["name"])
        try:
            _check_one(spec, standard_tail, standard_sha, manifest)
        except Exception as error:
            failures += 1
            print(f"{name}: FAIL ({type(error).__name__}: {error})")
        else:
            print(f"{name}: PASS (static source composition and six-API definitions)")
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
